export { IAdaptor } from './adaptor/adaptor';
export { AdaptorTypes } from './adaptor/adaptor-types';
export { ICol } from './interfaces/col';
export { IColResolver } from './interfaces/col-resolver';
export { IDoc } from './interfaces/doc';
export { IDocResolver } from './interfaces/doc-resolver';
export { IQuery } from './interfaces/query';
export { IQueryResolver } from './interfaces/query-resolver';
export { NewResource } from './resource';
