name: Tests
run-name: ${{ github.ref }} tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Node Version
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Cache pnpm
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install Dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: |
            - args: [--frozen-lockfile]
      - name: Test
        run: pnpm run build
