name: Tests
run-name: ${{ github.ref }} tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Node Version
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Test
        run: pnpm run test
